### ISSUE TITLE
Plots recipe for Shapefiles

### ISSUE THREAD

**Issue by mkborregaard** [JuliaGeo/Shapefile.jl#12]
Hi,
there is currently a Plots recipe for polygons shapefiles in PlotRecipes. It works reasonably well, though it cannot deal with polygons with holes, at the moment.
It would perhaps live more naturally in Shapefile, where it could be expanded to include other types of Shapefile etc. Would you be interested in a PR to move this? It would only involve adding a dependency to RecipesBase, a small macro with no further dependencies.

**Comment by yeesian** [comment]
Has anything changed since https://github.com/JuliaGeo/Shapefile.jl/pull/10?

If you're interested, given your involvement in the plots ecosystem, I'll be happy for you to lead the development on visualizations for geospatial geometries in JuliaGeo. But

1. there needs to be documentation (with worked examples) on how different kinds of geometries should be registered for use in Plots, be it as a gist, or a thread on https://discourse.julialang.org/c/domain/geo, and
2. the due process still applies: https://github.com/JuliaGeo/meta/wiki/How-to-get-Involved#join-the-juliageo-organization

**Comment by mkborregaard** [comment]
The only thing that changed was your invitation, the way I understood it, as the last comment here: https://github.com/yeesian/GeoDataFrames.jl/issues/1 :-)
I cannot commit to lead the development - I'd be happy to supply this recipe and over time write other recipes for other shapefile types, though.
Also,
1. Sure, and
2. Sure.

**Comment by yeesian** [comment]
I'll be willing to review a PR for this over at [GeoInterface](https://github.com/JuliaGeo/GeoInterface.jl) after #13 gets merged.
