### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Balinus** [JuliaGeo/Shapefile.jl#35]
Hello,

just updated to Julia 1.2.0 and tried installing and got the following error:

```julia
(v1.2) pkg> add Shapefile
[ Info: resolving package identifier `Shapefile` as a directory at `~/Shapefile`.
   Cloning git-repo `Shapefile`
ERROR: Git repository not found at 'Shapefile'
```
I've been able to install other packages. Not sure about the cause of the error. I was able to add the package on julia 1.1.1 on the same server.

**Comment by Balinus** [comment]
Adding with the https url works.

**Comment by visr** [comment]
Ha, what happens is, you have a directory in your working directory with the same name as this package.

https://github.com/JuliaLang/Pkg.jl/blob/a3349fb54a0e4592f75fc2aac9d3cd6d0090e509/src/REPLMode/argument_parsers.jl#L78-L80

So it decides to interpret it as a local path, but then fails since it is not a git repository. Interesting.

**Comment by Balinus** [comment]
Ah, indeed! Thanks!
