### ISSUE TITLE
Plot recipes?

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/Shapefile.jl#42]
It would be good if there was a Plots.jl recipe for `Handle` and `Table` so we could just do `plot(shp)` or `plot(table)`.

Any issues with adding a RecipesBase dependency?

**Comment by visr** [comment]
Sounds good to me, would be good to be able to plot them directly.

**Comment by yeesian** [comment]
(Not an objection if you all feel it's the right way to go, but since we've had a previous round of discussion in https://github.com/JuliaGeo/Shapefile.jl/issues/12 --) I'm curious how that compares to the possibility of indirectly getting plotting recipes via implementing the GeometryCollection interface for Handle / Table?

**Comment by rafaqz** [comment]
That sounds like a better option.

The only concern is that I doubt I would personally have time to do it (it's a bunch of new things to learn fo rme), and I already have a working version of the recipes. But if someone else has the time it sounds preferable.

**Comment by yeesian** [comment]
That's reasonable -- I'm for incremental progress and not letting perfect get in the way of the good

**Comment by visr** [comment]
This was fixed by #44. Just notice we haven't tagged a release since, will do so now.
