### ISSUE TITLE
How Do I Build a Shapefile.Table or Create a Subset of a Given Table?

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaGeo/Shapefile.jl#48]
I am filtering a Table right now with a simple for loop iterating over a Shapefile.Table as I saw that `filter` was not defined for Shapefile.Table. After I loop through my custom filter on the Table, I get a Row element back. Using these Shapefile.Row objects, how do I rebuild a new Table from my old Table? Thank you!

**Comment by visr** [comment]
Creating or updating Shapefile.Table isn't really supported right now, same as writing shapefiles. I don't think it is trivial to hack around it either, since besides updating the vector of shapes, you'd need to [update the .shp header](https://github.com/JuliaGeo/Shapefile.jl/blob/654e88053adc376de4b4e165a6418afc6462631e/src/Shapefile.jl#L126-L135), as well as the [data structures underlying the .dbf file](https://github.com/JuliaData/DBFTables.jl/blob/6b7ff043f9d5d9df0408006b7c612b9555a7315b/src/DBFTables.jl#L13-L33).

Would it be an option to convert the table to DataFrame? If you are interested in the plotting recipes defined on the Table, they are also defined on the individual geometries. Or you could give https://github.com/evetion/GeoDataFrames.jl a shot as well.

**Comment by TheCedarPrince** [comment]
Hey @visr - thanks for the quick response! Ah gotcha - reading it into a DataFrame is indeed a possibility. I do however need to access the polygon geometries which a DataFrame does not seem to support. Should I use GeoDataFrames.jl instead then in this case to get access to both the metadata and the geometries?

**Comment by visr** [comment]
Ah you're right the geometries are not included there by default. We should probably revise that at some point. Right now, to add the geometries to the DataFrame, you can do
```julia
df = DataFrame(table)
df["geometry"] = Shapefile.shapes(table)
```

**Comment by TheCedarPrince** [comment]
How hard would that functionality be to add @visr? I could do it as I have written a code base that relies pretty heavily on Shapefile.jl.

**Comment by visr** [comment]
I think it would be quite easy. The rows already contain the geometries:

https://github.com/JuliaGeo/Shapefile.jl/blob/654e88053adc376de4b4e165a6418afc6462631e/src/table.jl#L41-L44

I think we mainly need to add it to the Schema:

https://github.com/JuliaGeo/Shapefile.jl/blob/654e88053adc376de4b4e165a6418afc6462631e/src/table.jl#L71

**Comment by TheCedarPrince** [comment]
Ok, I will start making a draft PR on this @visr and will open a PR in a few minutes. Will try to finish it tomorrow

**Comment by visr** [comment]
And add it to getproperty, and propertynames as well, a few tests, etc. Would be great if you could work on it!

**Comment by TheCedarPrince** [comment]
I'm going ahead and closing this issue @visr since we got #49 merged! Thanks for the help and support :partying_face:
