### ISSUE TITLE
Is it possible to incorporate into a shapefile, extra columns ?

### ISSUE THREAD

**Issue by martinmestre** [JuliaGeo/Shapefile.jl#56]
Hi Martin @visr,
I would like to know if it is possible to merge a CVS file which contains two columns: e.g. "common" and "extra",
into a shapefile that contains geometry information (Polygons descripted by points) and column named "common" plus more columns.
If it is possible, which are the commands for that. If it is not possible, do you know of other packages that can do so ?
Thank  you very much in advance. 
Martín

**Comment by visr** [comment]
Do you want to write the results back to a shapefile after you merge the CSV file in? If so, this package does not have write support, so it cannot be used for that.

If you don't you could use this package to read the shapefile, convert it to a DataFrame and do a [join](https://dataframes.juliadata.org/stable/man/joins/) using that package.

It's also worth looking at https://github.com/evetion/GeoDataFrames.jl for this, since it has write support.

**Comment by ErickChacon** [comment]
Shouldn't this issue be closed given that it is possible using `Shapefile.write`?
